/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_util_NativeNCScale */

#ifndef _Included_org_apache_hadoop_util_NativeNCScale
#define _Included_org_apache_hadoop_util_NativeNCScale
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_hadoop_util_NativeNCScale
 * Method:    nativeInit
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_apache_hadoop_util_NativeNCScale_nativeInit
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_apache_hadoop_util_NativeNCScale
 * Method:    nativeCompute
 * Signature: ([Ljava/nio/ByteBuffer;I[Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_util_NativeNCScale_nativeCompute
  (JNIEnv *, jclass, jobjectArray, jint, jobjectArray, jint);

/*
 * Class:     org_apache_hadoop_util_NativeNCScale
 * Method:    nativeParityUpdate
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_util_NativeNCScale_nativeParityUpdate
  (JNIEnv *, jclass, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
